### ISSUE TITLE
"pip install elastix_napari" does not work

### ISSUE THREAD

**Issue by ntatsisk** [SuperElastix/elastix_napari#24]
"pip install elastix_napari" looks as if it works initially but then napari crashes on startup. Environment: `windows 10`, `python 3.9.16`, `napari 0.4.17`

The error is:
```
(napari-elastix-plugin) C:\> napari
Traceback (most recent call last):
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\qtpy\__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\__init__.py", line 9, in <module>
    from qtpy import API_NAME, QtCore
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\qtpy\__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\__main__.py", line 218, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_event_loop.py", line 2, in <module>
    from ._qt.qt_event_loop import gui_qt, run
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\__init__.py", line 12, in <module>
    raise type(e)(
TypeError: __init__() takes 1 positional argument but 2 were given
```
If I install `PySide6-Essentials` (`PySide6`) as indicated by the error, then I am getting 

```
(napari-elastix-plugin) C:\> python -m pip install PySide6-Essentials
Collecting PySide6-Essentials
  Using cached PySide6_Essentials-6.4.2-cp37-abi3-win_amd64.whl (77.2 MB)
Collecting shiboken6==6.4.2
  Using cached shiboken6-6.4.2-cp37-abi3-win_amd64.whl (1.5 MB)
Installing collected packages: shiboken6, PySide6-Essentials
Successfully installed PySide6-Essentials-6.4.2 shiboken6-6.4.2
(napari-elastix-plugin) C:\> napari
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
15:09:08 WARNING DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
Traceback (most recent call last):
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\__main__.py", line 327, in _run
    viewer = Viewer()
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\qt_main_window.py", line 463, in __init__
    self._qt_window = _QtMainWindow(viewer)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\qt_main_window.py", line 88, in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\qt_viewer.py", line 217, in __init__
    self._create_canvas()
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_qt\qt_viewer.py", line 401, in _create_canvas
    self.canvas = VispyCanvas(
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\napari\_vispy\canvas.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\scene\canvas.py", line 135, in __init__
    super(SceneCanvas, self).__init__(
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\app\canvas.py", line 211, in __init__
    self.create_native()
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\app\canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\app\backends\_qt.py", line 372, in __init__
    self._init_specific(p, kwargs)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\app\backends\_qt.py", line 791, in _init_specific
    glformat = _set_config(p.context.config)
  File "C:\Users\kntatsis\miniconda3\envs\napari-elastix-plugin\lib\site-packages\vispy\app\backends\_qt.py", line 283, in _set_config
    glformat.setSwapBehavior(glformat.DoubleBuffer if c['double_buffer']
AttributeError: 'PySide6.QtGui.QSurfaceFormat' object has no attribute 'DoubleBuffer'
(napari-elastix-plugin) C:\>
```

An alternative is to do "pip install napari[all]" in a fresh environment, and then install the plugin via the GUI plugin manager of napari. This approch allows the napari to start and also the plugin interface is displayed, however, any interaction throws errors as in https://github.com/SuperElastix/elastix_napari/issues/23.

(Note: currently I am getting the same message for any error so I am not exactly sure if the errors are indeed the same)
```
An error occurred while trying to format an error and show it in console.
You can try to uninstall IPython to disable rich traceback formatting
And/or report a bug to napari
```

**Comment by ntatsisk** [comment]
It is fixed with the new version `0.1.8`: https://pypi.org/project/elastix-napari/
